name: Update Airspace Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-airspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Process airspace data
        run: python process_airspace.py
        
      - name: Upload versioned airspace file
        uses: actions/upload-artifact@v4
        with:
          name: airspace-geojson
          path: airspace_*.geojson
          
      - name: Set current date as env variable
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Airspace Data ${{ env.RELEASE_DATE }}
          tag_name: release-${{ env.RELEASE_DATE }}
          files: |
            airspace.geojson
            airspace_*.geojson
          body: |
            Updated airspace data for ${{ env.RELEASE_DATE }}
            
            ### Stable URLs
            - Latest release: https://github.com/${{ github.repository }}/releases/latest
            - Direct download airspace.geojson: https://github.com/${{ github.repository }}/releases/latest/download/airspace.geojson
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 