name: Update Airspace Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-airspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to check for changes
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Process airspace data
        run: python process_airspace.py
        
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet HEAD airspace.geojson; then
            echo "No changes detected in airspace.geojson"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in airspace.geojson"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Upload versioned airspace file
        uses: actions/upload-artifact@v3
        with:
          name: airspace-geojson
          path: airspace_*.geojson
          
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add airspace.geojson airspace_*.geojson
          git commit -m "Update airspace data [skip ci]"
          git push
          
      - name: Set current date as env variable
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create Release
        if: steps.check_changes.outputs.changes_detected == 'true'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Airspace Data ${{ env.RELEASE_DATE }}
          tag_name: release-${{ env.RELEASE_DATE }}
          files: |
            airspace.geojson
            airspace_*.geojson
          body: |
            Updated airspace data for ${{ env.RELEASE_DATE }}
            
            ### Stable URLs
            - Latest release: https://github.com/${{ github.repository }}/releases/latest
            - Direct download airspace.geojson: https://github.com/${{ github.repository }}/releases/latest/download/airspace.geojson
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 