name: Update Airspace Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

# Explicitly set permissions needed for GitHub releases
permissions:
  contents: write
  
jobs:
  update-airspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Process airspace data (v2)
        id: process
        run: |
          cd v2
          # Clean up any old NO_CHANGES file from previous runs
          rm -f NO_CHANGES
          echo "Starting airspace processing..."
          
          # Run the Python script and capture exit code
          if python process_airspace.py; then
            echo "Python script completed successfully"
            
            # Check for NO_CHANGES file and set output accordingly
            if [ -f "NO_CHANGES" ]; then
              echo "changes=false" >> $GITHUB_OUTPUT
              echo "NO_CHANGES file found - skipping release creation"
              cat NO_CHANGES
            else
              echo "changes=true" >> $GITHUB_OUTPUT
              echo "NO_CHANGES file not found - will create a new release"
              # Verify output files exist
              if [ -f "airspace_with_france.geojson" ]; then
                echo "✓ airspace_with_france.geojson exists"
              else
                echo "✗ airspace_with_france.geojson missing"
                exit 1
              fi
              if [ -f "checksums.json" ]; then
                echo "✓ checksums.json exists"
              else
                echo "✗ checksums.json missing"
                exit 1
              fi
            fi
          else
            echo "Python script failed with exit code: $?"
            exit 1
          fi
          
      - name: Rename output file to maintain compatibility
        if: steps.process.outputs.changes == 'true'
        run: |
          cp v2/airspace_with_france.geojson airspace.geojson
          cp v2/checksums.json checksums.json
        
      - name: Set current date as env variable
        if: steps.process.outputs.changes == 'true'
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create Release
        if: steps.process.outputs.changes == 'true'
        uses: ncipollo/release-action@v1
        with:
          name: Airspace Data ${{ env.RELEASE_DATE }}
          tag: release-${{ env.RELEASE_DATE }}
          artifacts: "airspace.geojson,checksums.json"
          body: |
            Updated airspace data for ${{ env.RELEASE_DATE }}
            
            ### Stable URLs
            Direct download: https://github.com/${{ github.repository }}/releases/latest/download/airspace.geojson
            Checksums: https://github.com/${{ github.repository }}/releases/latest/download/checksums.json
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true 