name: Update Airspace Data

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

# Explicitly set permissions needed for GitHub releases
permissions:
  contents: write
  
jobs:
  update-airspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Process airspace data
        run: python process_airspace.py
        # Note: We're modifying process_airspace.py to no longer create versioned files
        
      - name: Set current date as env variable
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Airspace Data ${{ env.RELEASE_DATE }}
          tag: release-${{ env.RELEASE_DATE }}
          artifacts: airspace.geojson
          body: |
            Updated airspace data for ${{ env.RELEASE_DATE }}
            
            ### Stable URL
            Direct download: https://github.com/${{ github.repository }}/releases/latest/download/airspace.geojson
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true 